# \
CS 170 - Theory of Operating Systems\
By: Matthew S Montoya\
Purpose: Measure the time it takes for the OS to perform context swapping\
Last Modified: 12 February 2019

contextswap.o: contextswap.c
	gcc contextswap.c -o contextswap.o
clean:
	rm -f *.o